//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChristmasList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circle
    {
        public string PK_CircleID { get; set; }
        public string FK_User01 { get; set; }
        public string FK_User02 { get; set; }
        public string FK_User03 { get; set; }
        public string FK_User04 { get; set; }
        public string FK_User05 { get; set; }
        public string FK_User06 { get; set; }
        public string FK_User07 { get; set; }
        public string FK_User08 { get; set; }
        public string FK_User09 { get; set; }
        public string FK_User10 { get; set; }
        public string FK_User11 { get; set; }
        public string FK_User12 { get; set; }
        public string FK_User13 { get; set; }
        public string FK_User14 { get; set; }
        public string FK_User15 { get; set; }
    }
}
