//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChristmasList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Present
    {
        public string PK_PresentID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
