//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChristmasList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string PK_UserID { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string Number { get; set; }
        public string Street { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
    }
}
